export {
  GLOBAL_PANEL_QUERY,
  PROJECTS_LIST_QUERY,
  PROJECTS_PANEL_QUERY,
  EPOCHS_LIST_QUERY,
  EPOCHS_PANEL_QUERY,
  ENROLLMENTS_QUERY,
  BALANCE_LEAVES_QUERY,
} from "@/app/lib/graphql/matroid";
